### ISSUE TITLE
0 value placeholder.

### ISSUE THREAD

**Issue by kacan1999** [Artemis-the-gr8/PlayerStatsExpansion#29]
When position in top placeholder doesn't exist, that return placeholder name.
It should show "Position does not exist" (Maybe add position for that to config)

![image](https://user-images.githubusercontent.com/17888729/190005637-e8531bc9-2022-49a5-854a-7327b0eeaad0.png)

Console: 
![image](https://user-images.githubusercontent.com/17888729/190007186-1d910c4d-91ce-45b4-9629-7cd31804bfef.png)

![image](https://user-images.githubusercontent.com/17888729/190011862-961a89e9-38e3-4075-b6b8-5e5e4da952ef.png)

**Comment by Artemis-the-gr8** [comment]
You are correct, this is indeed a bug. I'm already working on a fix, which will be included in the next update!
