### ISSUE TITLE
Top N placeholder doesn't update positions

### ISSUE THREAD

**Issue by thejykim** [Artemis-the-gr8/PlayerStatsExpansion#39]
Hello!

I'm running into an issue with the PlayerStats expansion where PlaceholderAPI top N positions aren't updating. I've attached an example of it being out of sync.

I'm using this placeholder for the rankings (1-8):

`%playerstats_ top: 1, play_one_minute%`

A server restart fixes positions but isn't really viable as a solution going forward. Anything I can do to fix this?

Thanks!

**Comment by thejykim** [comment]
![Screenshot_37](https://user-images.githubusercontent.com/16480164/235308997-6ae34a35-9ef6-4374-96df-98adb8b7c2a1.png)

**Comment by Artemis-the-gr8** [comment]
Hello!

Which hologram mod are you using? Does that one have refresh/update settings? And what setting are you using for the time-statistic update interval in the PlayerStats section of the PlaceholderAPI config?

**Comment by thejykim** [comment]
Hi!

I'm using DecentHolograms and have the default 20 tick update interval. Here's the relevant config for that:

`
  display-range: 48
  update-range: 48
  update-interval: 20
  lru-cache-size: 500
`

 My PlayerStats PlaceholderAPI settings are to update every second as well:

`
  playerstats:
    update_interval_in_seconds:
      distance_statistics: 1
      time_statistics: 1
`

**Comment by Artemis-the-gr8** [comment]
Very odd that it doesn't update!
Is it only the time statistics that don't update, or also the distance statistics and general ones? 
If you check the placeholder with /papi parse, does that give the correct values, or have the same issue? 
And which Minecraft version and server type are you using?

**Comment by thejykim** [comment]
Sorry for the late response!

It's only the time statistic that doesn't update quickly. I'm also using Damage Dealt which updates normally.

However, it seems that Time Played does update, just takes longer than normal. I'm okay with this, I may have some interval setting off somewhere but for now I'll close the issue!

Thanks regardless.

**Comment by Artemis-the-gr8** [comment]
No worries!
I'm happy to hear the problem doesn't happen with all statistics, and that it still somewhat updates.

Feel free to let me know if it misbehaves more in the future, I can always look into it then!
