### ISSUE TITLE
How to display total world time in hours

### ISSUE THREAD

**Issue by Kalkoen31** [Artemis-the-gr8/PlayerStatsExpansion#47]
![2024-04-06_19 08 11](https://github.com/Artemis-the-gr8/PlayerStatsExpansion/assets/102528441/b9441a25-fd4d-4aa1-87f7-c1679d34352d)
I am currently using the playerstats plugin, papi plugin, and TAB plugin to display the playtime in tab. However I would like to know if it is possible to show the playtime in just the hours instead of Days + Hours + Minutes + Seconds since it takes up a lot of space (like shown in the screenshot).

I installed the expansion and used %Playerstats_ me, only:number, Total_World_Time% in the TAB config to display the playtime in the tablist.

I tried changing all of the following lines to hours, then reloading the statistic config reloading tab, however that did not work.
biggest-time-unit: hours
smallest-time-unit: hours
biggest-time-unit-for-hover-text: hours
smallest-time-unit-for-hover-text: hours

**Comment by Artemis-the-gr8** [comment]
Did you change those settings in the PlayerStats config, or in the PAPI config? For settings related to placeholders, you'll need to use the PAPI config (there's a PlayerStats section in there) - the PlayerStats config only controls the options for the command in chat.

**Comment by Kalkoen31** [comment]
Sorry for the late reaction, totally forgot about this. Changing "min_time_unit:" from second to hour in the PAPI config worked. Thank you for helping me :)
