### ISSUE TITLE
Why is it different? time

### ISSUE THREAD

**Issue by MrSmi1ey** [Artemis-the-gr8/PlayerStatsExpansion#48]
![3_2024-05-01_225136707](https://github.com/Artemis-the-gr8/PlayerStatsExpansion/assets/139050613/37258033-c6d2-448f-a407-c69c5ee4d300)
Why are the times different? ? ?

**Comment by MrSmi1ey** [comment]
Like, I want the tablist to display the time how long he played on my server

**Comment by Artemis-the-gr8** [comment]
You are using two different commands. The command in chat shows the top 10 by default if you don't specify a target, so your command there is the same as `/stat play_one_minute top`, while the tablist command you're using applies to the server total. The placeholder you're looking for is `%playerstats_ top:1, play_one_minute%`
